
name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_PAT }}
          external_repository: apollo-elements/apollo-elements
          publish_branch: gh-pages
          publish_dir: ./dist
          destination_dir: using-lit-apollo